// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.27.2

/* eslint-disable */

export * as ser from "./index.ser";
export * as cmd from "./index.cmd";
