// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.28.2
// source: jon_shared_cmd_cv.proto

/* eslint-disable */
import _m0 from 'protobufjs/minimal';
import { JonGuiDataVideoChannel, jonGuiDataVideoChannelFromJSON, jonGuiDataVideoChannelToJSON } from './jon_shared_data_types';

export interface Root {
  setAutoFocus?: SetAutoFocus | undefined;
  startTrackNdc?: StartTrackNDC | undefined;
  stopTrack?: StopTrack | undefined;
}

export interface SetAutoFocus {
  channel: JonGuiDataVideoChannel;
  value: boolean;
}

export interface StartTrackNDC {
  channel: JonGuiDataVideoChannel;
  x: number;
  y: number;
}

export interface StopTrack {
  channel: JonGuiDataVideoChannel;
}

function createBaseRoot(): Root {
  return { setAutoFocus: undefined, startTrackNdc: undefined, stopTrack: undefined };
}

export const Root = {
  encode(message: Root, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.setAutoFocus !== undefined) {
      SetAutoFocus.encode(message.setAutoFocus, writer.uint32(10).fork()).ldelim();
    }
    if (message.startTrackNdc !== undefined) {
      StartTrackNDC.encode(message.startTrackNdc, writer.uint32(18).fork()).ldelim();
    }
    if (message.stopTrack !== undefined) {
      StopTrack.encode(message.stopTrack, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Root {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.setAutoFocus = SetAutoFocus.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.startTrackNdc = StartTrackNDC.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.stopTrack = StopTrack.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Root {
    return {
      setAutoFocus: isSet(object.setAutoFocus) ? SetAutoFocus.fromJSON(object.setAutoFocus) : undefined,
      startTrackNdc: isSet(object.startTrackNdc) ? StartTrackNDC.fromJSON(object.startTrackNdc) : undefined,
      stopTrack: isSet(object.stopTrack) ? StopTrack.fromJSON(object.stopTrack) : undefined,
    };
  },

  toJSON(message: Root): unknown {
    const obj: any = {};
    if (message.setAutoFocus !== undefined) {
      obj.setAutoFocus = SetAutoFocus.toJSON(message.setAutoFocus);
    }
    if (message.startTrackNdc !== undefined) {
      obj.startTrackNdc = StartTrackNDC.toJSON(message.startTrackNdc);
    }
    if (message.stopTrack !== undefined) {
      obj.stopTrack = StopTrack.toJSON(message.stopTrack);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Root>, I>>(base?: I): Root {
    return Root.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Root>, I>>(object: I): Root {
    const message = createBaseRoot();
    message.setAutoFocus =
      object.setAutoFocus !== undefined && object.setAutoFocus !== null ? SetAutoFocus.fromPartial(object.setAutoFocus) : undefined;
    message.startTrackNdc =
      object.startTrackNdc !== undefined && object.startTrackNdc !== null ? StartTrackNDC.fromPartial(object.startTrackNdc) : undefined;
    message.stopTrack = object.stopTrack !== undefined && object.stopTrack !== null ? StopTrack.fromPartial(object.stopTrack) : undefined;
    return message;
  },
};

function createBaseSetAutoFocus(): SetAutoFocus {
  return { channel: 0, value: false };
}

export const SetAutoFocus = {
  encode(message: SetAutoFocus, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.channel !== 0) {
      writer.uint32(8).int32(message.channel);
    }
    if (message.value !== false) {
      writer.uint32(16).bool(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetAutoFocus {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetAutoFocus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.channel = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.value = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetAutoFocus {
    return {
      channel: isSet(object.channel) ? jonGuiDataVideoChannelFromJSON(object.channel) : 0,
      value: isSet(object.value) ? globalThis.Boolean(object.value) : false,
    };
  },

  toJSON(message: SetAutoFocus): unknown {
    const obj: any = {};
    if (message.channel !== 0) {
      obj.channel = jonGuiDataVideoChannelToJSON(message.channel);
    }
    if (message.value !== false) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetAutoFocus>, I>>(base?: I): SetAutoFocus {
    return SetAutoFocus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetAutoFocus>, I>>(object: I): SetAutoFocus {
    const message = createBaseSetAutoFocus();
    message.channel = object.channel ?? 0;
    message.value = object.value ?? false;
    return message;
  },
};

function createBaseStartTrackNDC(): StartTrackNDC {
  return { channel: 0, x: 0, y: 0 };
}

export const StartTrackNDC = {
  encode(message: StartTrackNDC, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.channel !== 0) {
      writer.uint32(8).int32(message.channel);
    }
    if (message.x !== 0) {
      writer.uint32(21).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(29).float(message.y);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StartTrackNDC {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartTrackNDC();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.channel = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.x = reader.float();
          continue;
        case 3:
          if (tag !== 29) {
            break;
          }

          message.y = reader.float();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartTrackNDC {
    return {
      channel: isSet(object.channel) ? jonGuiDataVideoChannelFromJSON(object.channel) : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: StartTrackNDC): unknown {
    const obj: any = {};
    if (message.channel !== 0) {
      obj.channel = jonGuiDataVideoChannelToJSON(message.channel);
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StartTrackNDC>, I>>(base?: I): StartTrackNDC {
    return StartTrackNDC.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartTrackNDC>, I>>(object: I): StartTrackNDC {
    const message = createBaseStartTrackNDC();
    message.channel = object.channel ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

function createBaseStopTrack(): StopTrack {
  return { channel: 0 };
}

export const StopTrack = {
  encode(message: StopTrack, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.channel !== 0) {
      writer.uint32(8).int32(message.channel);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StopTrack {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStopTrack();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.channel = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StopTrack {
    return { channel: isSet(object.channel) ? jonGuiDataVideoChannelFromJSON(object.channel) : 0 };
  },

  toJSON(message: StopTrack): unknown {
    const obj: any = {};
    if (message.channel !== 0) {
      obj.channel = jonGuiDataVideoChannelToJSON(message.channel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StopTrack>, I>>(base?: I): StopTrack {
    return StopTrack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StopTrack>, I>>(object: I): StopTrack {
    const message = createBaseStopTrack();
    message.channel = object.channel ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
