// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.28.2
// source: jon_shared_data_camera_heat.proto

/* eslint-disable */
import _m0 from 'protobufjs/minimal';
import {
  JonGuiDataFxModeHeat,
  jonGuiDataFxModeHeatFromJSON,
  jonGuiDataFxModeHeatToJSON,
  JonGuiDataVideoChannelHeatAGCModes,
  jonGuiDataVideoChannelHeatAGCModesFromJSON,
  jonGuiDataVideoChannelHeatAGCModesToJSON,
  JonGuiDataVideoChannelHeatFilters,
  jonGuiDataVideoChannelHeatFiltersFromJSON,
  jonGuiDataVideoChannelHeatFiltersToJSON,
} from './jon_shared_data_types';

export interface JonGuiDataCameraHeat {
  zoomPos: number;
  agcMode: JonGuiDataVideoChannelHeatAGCModes;
  filter: JonGuiDataVideoChannelHeatFilters;
  autoFocus: boolean;
  zoomTablePos: number;
  zoomTablePosMax: number;
  ddeLevel: number;
  ddeEnabled: boolean;
  fxMode: JonGuiDataFxModeHeat;
}

function createBaseJonGuiDataCameraHeat(): JonGuiDataCameraHeat {
  return {
    zoomPos: 0,
    agcMode: 0,
    filter: 0,
    autoFocus: false,
    zoomTablePos: 0,
    zoomTablePosMax: 0,
    ddeLevel: 0,
    ddeEnabled: false,
    fxMode: 0,
  };
}

export const JonGuiDataCameraHeat = {
  encode(message: JonGuiDataCameraHeat, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.zoomPos !== 0) {
      writer.uint32(13).float(message.zoomPos);
    }
    if (message.agcMode !== 0) {
      writer.uint32(16).int32(message.agcMode);
    }
    if (message.filter !== 0) {
      writer.uint32(24).int32(message.filter);
    }
    if (message.autoFocus !== false) {
      writer.uint32(32).bool(message.autoFocus);
    }
    if (message.zoomTablePos !== 0) {
      writer.uint32(40).int32(message.zoomTablePos);
    }
    if (message.zoomTablePosMax !== 0) {
      writer.uint32(48).int32(message.zoomTablePosMax);
    }
    if (message.ddeLevel !== 0) {
      writer.uint32(56).int32(message.ddeLevel);
    }
    if (message.ddeEnabled !== false) {
      writer.uint32(64).bool(message.ddeEnabled);
    }
    if (message.fxMode !== 0) {
      writer.uint32(72).int32(message.fxMode);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): JonGuiDataCameraHeat {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJonGuiDataCameraHeat();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 13) {
            break;
          }

          message.zoomPos = reader.float();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.agcMode = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.filter = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.autoFocus = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.zoomTablePos = reader.int32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.zoomTablePosMax = reader.int32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.ddeLevel = reader.int32();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.ddeEnabled = reader.bool();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.fxMode = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JonGuiDataCameraHeat {
    return {
      zoomPos: isSet(object.zoomPos) ? globalThis.Number(object.zoomPos) : 0,
      agcMode: isSet(object.agcMode) ? jonGuiDataVideoChannelHeatAGCModesFromJSON(object.agcMode) : 0,
      filter: isSet(object.filter) ? jonGuiDataVideoChannelHeatFiltersFromJSON(object.filter) : 0,
      autoFocus: isSet(object.autoFocus) ? globalThis.Boolean(object.autoFocus) : false,
      zoomTablePos: isSet(object.zoomTablePos) ? globalThis.Number(object.zoomTablePos) : 0,
      zoomTablePosMax: isSet(object.zoomTablePosMax) ? globalThis.Number(object.zoomTablePosMax) : 0,
      ddeLevel: isSet(object.ddeLevel) ? globalThis.Number(object.ddeLevel) : 0,
      ddeEnabled: isSet(object.ddeEnabled) ? globalThis.Boolean(object.ddeEnabled) : false,
      fxMode: isSet(object.fxMode) ? jonGuiDataFxModeHeatFromJSON(object.fxMode) : 0,
    };
  },

  toJSON(message: JonGuiDataCameraHeat): unknown {
    const obj: any = {};
    if (message.zoomPos !== 0) {
      obj.zoomPos = message.zoomPos;
    }
    if (message.agcMode !== 0) {
      obj.agcMode = jonGuiDataVideoChannelHeatAGCModesToJSON(message.agcMode);
    }
    if (message.filter !== 0) {
      obj.filter = jonGuiDataVideoChannelHeatFiltersToJSON(message.filter);
    }
    if (message.autoFocus !== false) {
      obj.autoFocus = message.autoFocus;
    }
    if (message.zoomTablePos !== 0) {
      obj.zoomTablePos = Math.round(message.zoomTablePos);
    }
    if (message.zoomTablePosMax !== 0) {
      obj.zoomTablePosMax = Math.round(message.zoomTablePosMax);
    }
    if (message.ddeLevel !== 0) {
      obj.ddeLevel = Math.round(message.ddeLevel);
    }
    if (message.ddeEnabled !== false) {
      obj.ddeEnabled = message.ddeEnabled;
    }
    if (message.fxMode !== 0) {
      obj.fxMode = jonGuiDataFxModeHeatToJSON(message.fxMode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JonGuiDataCameraHeat>, I>>(base?: I): JonGuiDataCameraHeat {
    return JonGuiDataCameraHeat.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JonGuiDataCameraHeat>, I>>(object: I): JonGuiDataCameraHeat {
    const message = createBaseJonGuiDataCameraHeat();
    message.zoomPos = object.zoomPos ?? 0;
    message.agcMode = object.agcMode ?? 0;
    message.filter = object.filter ?? 0;
    message.autoFocus = object.autoFocus ?? false;
    message.zoomTablePos = object.zoomTablePos ?? 0;
    message.zoomTablePosMax = object.zoomTablePosMax ?? 0;
    message.ddeLevel = object.ddeLevel ?? 0;
    message.ddeEnabled = object.ddeEnabled ?? false;
    message.fxMode = object.fxMode ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
